
export enum TcfError {
	OTHER               = 1,
    JSON_SYNTAX         = 2,
    PROTOCOL            = 3,
    BUFFER_OVERFLOW     = 4,
    CHANNEL_CLOSED      = 5,
    COMMAND_CANCELLED   = 6,
    UNKNOWN_PEER        = 7,
    BASE64              = 8,
    EOF                 = 9,
    ALREADY_STOPPED     = 10,
    ALREADY_EXITED      = 11,
    ALREADY_RUNNING     = 12,
    ALREADY_ATTACHED    = 13,
    IS_RUNNING          = 14,
    INV_DATA_SIZE       = 15,
    INV_CONTEXT         = 16,
    INV_ADDRESS         = 17,
    INV_EXPRESSION      = 18,
    INV_FORMAT          = 19,
    INV_NUMBER          = 20,
    INV_DWARF           = 21,
    SYM_NOT_FOUND       = 22,
    UNSUPPORTED         = 23,
    INV_DATA_TYPE       = 24,
    INV_COMMAND         = 25,
}